version: '3.4'

networks:
  kanbanNetwork:

services:

  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    depends_on:
      - webapi
      - frontend
      - SqlServerDb
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - kanbanNetwork

  SqlServerDb:
    container_name: sql_server_kanban
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=A&VeryComplex123Password
    networks:
      - kanbanNetwork
  webapi:
    image: kanban
    build:
      dockerfile: Dockerfile
    depends_on:
      - SqlServerDb
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - kanbanNetwork
   
  frontend:
    image: frontend
    depends_on:
      - webapi
    build:
      dockerfile: Kanban-Board-Frontend/Dockerfile
    networks:
      - kanbanNetwork


  # frontend:
  #   image: kanban-frontend
  #   build:
  #     context: .
  #     dockerfile: Kanban-Board-Frontend/Dockerfile
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - webapi
  #   environment:
  #     - apiUrl=http://webapi:80
  #     - baseUrl=http://localhost:8080

