version: '3.4'

networks:
  kanbanNetwork:

services:

  nginx:
    container_name: reverse-proxy
    image: ashwor11/kanban-nginx-reverse-proxy
    build:
      dockerfile: Dockerfile
      context: ./nginx
    depends_on:
      - webapi
      - frontend
    ports:
      - 80:80
      - 443:443
    networks:
      - kanbanNetwork

  # SqlServerDb:
  #   container_name: sql_server_kanban
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   ports:
  #     - 1433:1433
  #   environment:
  #     - ACCEPT_EULA=y
  #     - MSSQL_SA_PASSWORD=A&VeryComplex123Password
  #   networks:
  #     - kanbanNetwork
  webapi:
    image: ashwor11/kanban-api
    build:
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:7011
    networks:
      - kanbanNetwork
    ports:  
      - 7011:7011
   
  frontend:
    image: ashwor11/kanban-frontend
    depends_on:
      - webapi
    build:
      context: ./Kanban-Board-Frontend
    networks:
      - kanbanNetwork


  # frontend:
  #   image: kanban-frontend
  #   build:
  #     context: .
  #     dockerfile: Kanban-Board-Frontend/Dockerfile
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - webapi
  #   environment:
  #     - apiUrl=http://webapi:80
  #     - baseUrl=http://localhost:8080

